### ISSUE TITLE
Non-expiring subscription not working.

### ISSUE THREAD

**Issue by crowesn** [uclibs/ojs3#37]
Open ended subscription type (subscription without expiration date) does not grant access to restricted content.

Tested on QA with production data.

**Comment by crowesn** [comment]
https://forum.pkp.sfu.ca/t/non-expiring-indivudal-subscriptions-no-access-to-pdfs-ojs-3-2-1-3/65531

**Comment by scherztc** [comment]
Closed by JIRA : https://ucdts.atlassian.net/browse/LIBOJS-18?atlOrigin=eyJpIjoiNDkwMWQ4YWVhYzU4NGIwMzgzODhiMTgyNTA0NzI0NmQiLCJwIjoiaiJ9
