### ISSUE TITLE
Create docker build

### ISSUE THREAD

**Issue by crowesn** [uclibs/ojs3#38]
Create a docker build for OJS development.

**Comment by crowesn** [comment]
https://github.com/uclibs/ojs-docker

**Comment by scherztc** [comment]
Closed by JIRA : https://ucdts.atlassian.net/browse/LIBOJS-19?atlOrigin=eyJpIjoiMzcwYjNjMDY1MDM4NGQ1MWE5MzVlZjc2ZTk4Mjg3OTMiLCJwIjoiaiJ9
