### ISSUE TITLE
Unable to re-publish after un-publish for xml uploaded works

### ISSUE THREAD

**Issue by crowesn** [uclibs/ojs3#39]
With works loaded via xml upload tool, when un-published , the system will not allow republishing without going through the copy-edit and review workflows. 

This bug is not encountered with submissions that came through quick-submit.

**Comment by scherztc** [comment]
Closed by JIRA : https://ucdts.atlassian.net/browse/LIBOJS-20?atlOrigin=eyJpIjoiYTc5YzE3MTRiMGZiNDhhNGI0YzA4YmZjY2FhNjBhN2UiLCJwIjoiaiJ9
