### ISSUE TITLE
Configure and activate ORCID plugin

### ISSUE THREAD

**Issue by crowesn** [uclibs/ojs3#47]
Via Mark Konecny and Amy Koshoffer.

1. Confirm ongoing member subscription. 
1. If membership continues, configure with member credentials
1. Activate.

**Comment by scherztc** [comment]
Closed by JIRA : https://ucdts.atlassian.net/browse/LIBOJS-21?atlOrigin=eyJpIjoiYWE3NTc3OTVhZmMwNGQxNGI2MWVhMTg1NjIyNWQxYTkiLCJwIjoiaiJ9
