### ISSUE TITLE
Configure Portico plugin.

### ISSUE THREAD

**Issue by crowesn** [uclibs/ojs3#49]
https://info.orcid.org/introducing-the-new-ojs-orcid-plugin/

**Comment by scherztc** [comment]
Closed by JIRA : https://ucdts.atlassian.net/browse/LIBOJS-22?atlOrigin=eyJpIjoiZDMxNjFlZTExNjM2NDZiYmFiMjRlZWM3NjlhNDgwOTQiLCJwIjoiaiJ9
