### ISSUE TITLE
Subscription Notification emails are never sent out

### ISSUE THREAD

**Issue by crowesn** [uclibs/ojs3#58]
Other emails are generating without issue.
Tested creating new subscription with smtp deactivated, no errors encountered, no email generated.

See https://github.com/pkp/pkp-lib/issues/6596

**Comment by scherztc** [comment]
Closed by JIRA : https://ucdts.atlassian.net/browse/LIBOJS-17?atlOrigin=eyJpIjoiNTJmNWU4ZmFjODA1NDg4N2E4MTA1Zjc4NGQ2OTZiYjUiLCJwIjoiaiJ9
