### ISSUE TITLE
Upgrade to 3.2x

### ISSUE THREAD

**Issue by crowesn** [uclibs/ojs3#6]
https://pkp.sfu.ca/ojs/UPGRADE

http://pkp.sfu.ca/ojs/download/ojs-3.1.2-4.tar.gz

**Comment by hortongn** [comment]
@crowesn Will you be upgrading to v3.2.0?  If so, please update the issue title.

**Comment by hortongn** [comment]
Post-upgrade things to check
* Are they still on reCAPTCHA v2?
* Did it affect the security header vulnerability InfoSec reported?
* Did it affect the password auto-complete vulnerability InfoSec reported?
